//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isa4enkoProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class applicant
    {
        public string id_applicant { get; set; }
        public string fist_name { get; set; }
        public string name { get; set; }
        public string middle_name { get; set; }
        public System.DateTime date_of_bth { get; set; }
        public string gender { get; set; }
        public string edication { get; set; }
        public string post { get; set; }
        public string roles { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    }
}
