//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isa4enkoProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class deals
    {
        public string id_deals { get; set; }
        public string id_vacancy { get; set; }
        public string id_applicants { get; set; }
        public string id_agent { get; set; }
        public System.DateTime date { get; set; }
    }
}
