//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isa4enkoProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public string id_roles { get; set; }
        public string name { get; set; }
    
        public virtual Employer Employer { get; set; }
    }
}
