//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isa4enkoProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class User1
    {
        public int userId { get; set; }
        public string userlogin { get; set; }
        public string userpassword { get; set; }
        public Nullable<int> id_roles { get; set; }
    }
}
