//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isa4enkoProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacancy
    {
        public string id_vacancy { get; set; }
        public System.DateTime date { get; set; }
        public string post { get; set; }
        public string edication { get; set; }
        public string languages { get; set; }
        public string gender { get; set; }
        public string salary { get; set; }
        public string driving_license { get; set; }
        public string working_conditions { get; set; }
    }
}
